# Generated by Django 3.2.21 on 2024-01-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='file',
            field=models.ImageField(upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
