# Generated by Django 3.2.21 on 2024-01-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240105_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='file',
            field=models.ImageField(upload_to='home/templates/'),
        ),
    ]
