# Generated by Django 3.2.21 on 2024-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_imagedata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
