# Generated by Django 3.2.21 on 2024-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_imagedata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='POINT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.BigIntegerField()),
            ],
        ),
    ]
